#ifndef DESKTOPNOTIFICATION_GLOBAL_H
#define DESKTOPNOTIFICATION_GLOBAL_H

#include <QtGlobal>

#ifdef NAUGHTY_EXPORT
#define NAUGHTY_LIBRARY Q_DECL_EXPORT
#elif defined(NAUGHTY_IMPORT)
#define NAUGHTY_LIBRARY Q_DECL_IMPORT
#endif

#endif // DESKTOPNOTIFICATION_GLOBAL_H
